### ISSUE TITLE
how i get data from api endpoints

### ISSUE THREAD

**Issue by kool-8** [pancakeswap/pancake-info-api#11]
i try to access  `https://api.pancakeswap.info/api/summary` but this page shows 
```
{"error":{"code":500,"message":"Failed to decode `block.number` value: `subgraph QmUf1YRkpWGSp867mLb6ab8aGPCnircwN17SKbrM5UeUW2 has only indexed up to block number 4626465 and data for block number 5306317 is therefore not yet available`"}}
```
how can i access endpoints? is it graphql? or rest ?

**Comment by alejoes** [comment]
> i try to access `https://api.pancakeswap.info/api/summary` but this page shows
> 
> ```
> {"error":{"code":500,"message":"Failed to decode `block.number` value: `subgraph QmUf1YRkpWGSp867mLb6ab8aGPCnircwN17SKbrM5UeUW2 has only indexed up to block number 4626465 and data for block number 5306317 is therefore not yet available`"}}
> ```
> 
> how can i access endpoints? is it graphql? or rest ?

hey, I ran into the same issue, it looks like it is a graphql which I'm not familiar with, I'm doing some tutorials in order to be able to learn, pls contact me if you'd like to share ideas escalantex.alejo@gmail.com

**Comment by ChefKai** [comment]
Hello, this issue is fixed; feel free to re-open the issue if the problem persist on your side. Thanks.

The endpoints are REST, and using GraphQL in the background to query data.

**Comment by dxblouie** [comment]
This issue is affecting our front-end in some countries today.
`{"error":{"code":500,"message":"GraphQL error: Failed to decode `block.number` value: `subgraph QmP7e1CxtrQSV9aFCEqLtgdJKPmoUsX3hfLFNkwXYosXei has only indexed up to block number 8087403 and data for block number 8147423 is therefore not yet available`"}}`

**Comment by rs21k** [comment]
The issue is still there. When we try to use the api in the local machine it is working but when we deploy it in our cloud server api is throwing error.

**Comment by gl4ukg** [comment]
I'm having same issue here: **Failed to decode `block.number` value: `subgraph QmUf1YRkpWGSp867mLb6ab8aGPCnircwN17SKbrM5UeUW2 has only indexed up to block number 5169885 and data for block number 8385027 is therefore not yet available`"** If anyone has solved this please help I'm new with graphql

**Comment by quanghvit** [comment]
@Glaukg I'm having same issue. could you share me solution if resolved it.
