### ISSUE TITLE
Api req error

### ISSUE THREAD

**Issue by berkcansmet** [pancakeswap/pancake-info-api#14]
I reviewed https://github.com/pancakeswap/pancake-info-api. https://api.pancakeswap.info/api/summary as a result when I make a request {
"error": {
"code": 500,
"message": "Failed to decode` block.number` value: `subgraph QmUf1YRkpWGSp867mLb6ab8aGPCnircwN17SKbrM5UeUW2 has only indexed up to block number 5081101 and data for block number 5665851 is therefore not yet available`"
}
} returns. What does it originate from?

I would be glad if you could help.

**Comment by ChefKai** [comment]
Hello, this issue is fixed; feel free to re-open the issue if the problem persist on your side. Thanks.

The error message originate from the subgraph not being updated to the latest block - 24 hours.

**Comment by amiralirang98** [comment]
i just now made a fetch request to https://api.pancakeswap.info/api/v2/summary but it is giving me error code 500 
message="first block was not fetched"

**Comment by MetaDex-M** [comment]
Hi I have same error with our token.
Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 18083597 and data for block number 18083824 is therefore not yet available.

Please can you help with this. its not displaying price for our token on pancake.
Token contract address 0x558ad2b02cE979Ca54F88206ED8597c8c740774E

**Comment by AlexeyUsachevWork** [comment]
Hi I have same error with our token.

We have got the errors in the browser console when we open Liquidity Pool page. 
The info about Liquidity Pool doesn't show on the page. 

**The Liquidity Pool is METALLIKA/USDT:** https://pancakeswap.finance/info/pool/0x81c8c65da9b448a4cb1c0fa233d94056ed659b84
**Token contract (METALLIKA) address**: 0xee3081b6bb20fc28f77c179658e9ca5978d48170

Errors: 

Failed to fetch pool data Error: Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 18919322 and data for block number 19024884 is therefore not yet available`: {"response":{"errors":[{"message":"Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 18919322 and data for block number 19024884 is therefore not yet available`"}],"status":200,"headers":{"map":{"content-length":"234","content-type":"application/json"}}},"request":{"query":"\n      query pools {\n        now: pairs(\n    where: { id_in: [\"undefined\",\"0x81c8c65da9b448a4cb1c0fa233d94056ed659b84\"] }\n    \n    orderBy: trackedReserveBNB\n    orderDirection: desc\n  ) {\n    id\n    reserve0\n    reserve1\n    reserveUSD\n    volumeUSD\n    token0Price\n    token1Price\n    token0 {\n      id\n      symbol\n      name\n    }\n    token1 {\n      id\n      symbol\n      name\n    }\n  }\n        oneDayAgo: pairs(\n    where: { id_in: [\"undefined\",\"0x81c8c65da9b448a4cb1c0fa233d94056ed659b84\"] }\n    block: {number: 19024884}\n    orderBy: trackedReserveBNB\n    orderDirection: desc\n  ) {\n    id\n    reserve0\n    reserve1\n    reserveUSD\n    volumeUSD\n    token0Price\n    token1Price\n    token0 {\n      id\n      symbol\n      name\n    }\n    token1 {\n      id\n      symbol\n      name\n    }\n  }\n        twoDaysAgo: pairs(\n    where: { id_in: [\"undefined\",\"0x81c8c65da9b448a4cb1c0fa233d94056ed659b84\"] }\n    block: {number: 18996107}\n    orderBy: trackedReserveBNB\n    orderDirection: desc\n  ) {\n    id\n    reserve0\n    reserve1\n    reserveUSD\n    volumeUSD\n    token0Price\n    token1Price\n    token0 {\n      id\n      symbol\n      name\n    }\n    token1 {\n      id\n      symbol\n      name\n    }\n  }\n        oneWeekAgo: pairs(\n    where: { id_in: [\"undefined\",\"0x81c8c65da9b448a4cb1c0fa233d94056ed659b84\"] }\n    block: {number: 18852533}\n    orderBy: trackedReserveBNB\n    orderDirection: desc\n  ) {\n    id\n    reserve0\n    reserve1\n    reserveUSD\n    volumeUSD\n    token0Price\n    token1Price\n    token0 {\n      id\n      symbol\n      name\n    }\n    token1 {\n      id\n      symbol\n      name\n    }\n  }\n        twoWeeksAgo: pairs(\n    where: { id_in: [\"undefined\",\"0x81c8c65da9b448a4cb1c0fa233d94056ed659b84\"] }\n    block: {number: 18651901}\n    orderBy: trackedReserveBNB\n    orderDirection: desc\n  ) {\n    id\n    reserve0\n    reserve1\n    reserveUSD\n    volumeUSD\n    token0Price\n    token1Price\n    token0 {\n      id\n      symbol\n      name\n    }\n    token1 {\n      id\n      symbol\n      name\n    }\n  }\n      }\n    "}}

Failed to fetch info overview Error: Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 18919322 and data for block number 19024884 is therefore not yet available`: {"response":{"errors":[{"message":"Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 18919322 and data for block number 19024884 is therefore not yet available`"}],"status":200,"headers":{"map":{"content-length":"234","content-type":"application/json"}}},"request":{"query":"query overview {\n      pancakeFactories(\n        block: { number: 19024884}\n        first: 1) {\n        totalTransactions\n        totalVolumeUSD\n        totalLiquidityUSD\n      }\n    }"}}

instrument.js:109 Failed to fetch info overview Error: Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 18919322 and data for block number 18996107 is therefore not yet available`: {"response":{"errors":[{"message":"Failed to decode `block.number` value: `subgraph Qmc3Q7LkXbwfDpTVAoiFbaMCjGqqS6bmMQdP7MZisdWMBg has only indexed up to block number 18919322 and data for block number 18996107 is therefore not yet available`"}],"status":200,"headers":{"map":{"content-length":"234","content-type":"application/json"}}},"request":{"query":"query overview {\n      pancakeFactories(\n        block: { number: 18996107}\n        first: 1) {\n        totalTransactions\n        totalVolumeUSD\n        totalLiquidityUSD\n      }\n    }"}}


Please can you help with this.

**Comment by fdagher** [comment]
This issue is back, any call to any api endpoint results in this error

**Comment by MetaDex-M** [comment]
https://pancakeswap.finance/info/token/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82
Nothing is loading on any token under the Info. Just a spinning pan. Tried
different PC and verified it with different users from Canada and the US

Please can you get this sorted out.
