### ISSUE TITLE
LP token price API or formula

### ISSUE THREAD

**Issue by cochinada** [pancakeswap/pancake-info-api#29]
I want to create a query in Excel for getting LP price for some pairs. How can I do that?
The 3 API-s that exist won-t do this.

**Comment by ChefKai** [comment]
Hello, there is no API endpoint planned for this; the best solution is to refer to the logic of our SDK ([pancakeswap/pancakeswap-sdk](https://github.com/pancakeswap/pancakeswap-sdk/blob/master/src/entities/pair.ts#L189)) and use the formula inside your Excel.
