### ISSUE TITLE
Can't use API endpoints

### ISSUE THREAD

**Issue by vinivst** [pancakeswap/pancake-info-api#31]
Hello there, i'm following the docs in https://github.com/pancakeswap/pancake-info-api/blob/develop/documentation.md but i just can't get any response, i tried the GET https://api.pancakeswap.info/api/tokens/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82 as the examples says but i only got this error:

{"message":"Missing Authentication Token"}

Can you help me?

Thanks.

**Comment by segersniels** [comment]
cc @ChefKai

**Comment by MarcChapar** [comment]
Same problem here.
Issue seems to be related to that specific endpoint  https://api.pancakeswap.info/api/tokens/{address}
Other endpoints are working fine for me.

**Comment by segersniels** [comment]
> Same problem here.
> Issue seems to be related to that specific endpoint [https://api.pancakeswap.info/api/tokens/{address}](https://api.pancakeswap.info/api/tokens/%7Baddress%7D)
> Other endpoints are working fine for me.

https://api.pancakeswap.info/api/summary is also busted

**Comment by cluchetto** [comment]
by the way, do you know why there is such a discrepancy between API values and pancakeswap values? (+20 USDT for CAKE for example)

**Comment by ChefKai** [comment]
Hello, thank you everyone for your reports; we will be addressing each of them today after the release of the Easter Battle!

**Comment by ChefKai** [comment]
> by the way, do you know why there is such a discrepancy between API values and pancakeswap values? (+20 USDT for CAKE for example)

Hello, are you able to share an example? Checked both API/subgraph and current blockchain data and could not find any discrepancy

**Comment by vinivst** [comment]
> Hello, thank you everyone for your reports; we will be addressing each of them today after the release of the Easter Battle!

Thanks for answering us, just tested and the summary endpoint is working now (https://api.pancakeswap.info/api/summary), the https://api.pancakeswap.info/api/tokens/{address} endpoint still broken, tho.

**Comment by ChefKai** [comment]
Hello, this endpoint (`/tokens/0x...`) is only available for testing right now (develop branch); and has not been released to production yet. All the of non-existing endpoints on the codebase will return this error.

You can also follow the release of these endpoints here: https://github.com/pancakeswap/pancake-info-api/issues/10#issuecomment-811879752
