### ISSUE TITLE
Adding more information 

### ISSUE THREAD

**Issue by SafeerHafiz** [pancakeswap/pancake-info-api#33]
Hi
I've just used this API for a telegram price bot and it's working amazing. However, I had one issue which was that only the USD value and BNB value of the coins are visible. It would be great if you could add values for USDT, EUR, GBP and all the main currencies.

**Comment by ChefKai** [comment]
Hello, this is not possible to do on a subgraph, but I would suggest you to use the `price_BNB` field, then get the price in the currency that you would like to support using Binance.com API endpoint; doing so you will be able to get USDT, TRY, EUR, BRL, GBP, AUD, ...
