### ISSUE TITLE
Missing Authentication Token

### ISSUE THREAD

**Issue by nickbencino** [pancakeswap/pancake-info-api#35]
When I try to return token information based on address.

`GET https://api.pancakeswap.info/api/tokens/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82`

I get the "Missing Authentication Token" error.

**Comment by ChefKai** [comment]
Hello, this endpoint is only available for testing right now (`develop` branch); and has not been released to production yet.
You can also follow the release of these endpoints here: https://github.com/pancakeswap/pancake-info-api/issues/10#issuecomment-811879752
All the of non-existing endpoints on the codebase will return this error.

**Comment by larumanaulo** [comment]
Hi @ChefKai ,

Will that endpoint be available to public use anytime soon?

Thanks
