### ISSUE TITLE
Missing Authentication Token

### ISSUE THREAD

**Issue by ProfMiracle** [pancakeswap/pancake-info-api#37]
The single token fetch endpoint is throwing an error message:

{"message":"Missing Authentication Token"}

No parameter was meant to be passed to it.

**Comment by ChefKai** [comment]
Hello, this endpoint is only available for testing right now (`develop` branch); and has not been released to production yet.
You can also follow the release of these endpoints here: https://github.com/pancakeswap/pancake-info-api/issues/10#issuecomment-811879752
All the of non-existing endpoints on the codebase will return this error.

**Comment by ProfMiracle** [comment]
gracias
