### ISSUE TITLE
tokens api error

### ISSUE THREAD

**Issue by caochangshan** [pancakeswap/pancake-info-api#39]
GET https://api.pancakeswap.info/api/tokens/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82

Response
{
    "message": "Missing Authentication Token"
}

Can not be used normally

**Comment by fdharamshi** [comment]
Same error. Did you find how to get an auth token? @caochangshan 
@ChefKai What to do?

**Comment by stychu** [comment]
Still under development. See this thread 
https://github.com/pancakeswap/pancake-info-api/issues/10
It should be released sometime this week or next according to the developer

**Comment by ChefKai** [comment]
Hello, this endpoint is only available for testing right now (`develop` branch); and has not been released to production yet.
You can also follow the release of these endpoints here: https://github.com/pancakeswap/pancake-info-api/issues/10#issuecomment-811879752
All the of non-existing endpoints on the codebase will return this error.
