### ISSUE TITLE
Error 500 after installing

### ISSUE THREAD

**Issue by bardolf69** [pancakeswap/pancake-info-api#42]
Hi folks,

I've followed the install instruction but when I query my endpoints I get 

```
"error": {
        "code": 500,
        "message": "Store error: query execution failed: Subgraph `pancakeswap/exchange-lite` not found"
    }
```
Did I miss something?

**Comment by ChefKai** [comment]
Thanks for reporting! The subgraph has been moved to a new endpoint to accomodate both `v1` and `v2` versions, we will update the documentation; you can also refer to the [pancakeswap/pancake-subgraph](https://github.com/pancakeswap/pancake-subgraph) repository.

**Comment by qnxdev** [comment]
Where can I find the correct endpoint?
