### ISSUE TITLE
Please update our token in your api

### ISSUE THREAD

**Issue by achtools** [pancakeswap/pancake-info-api#43]
https://api.pancakeswap.info/api/tokens/0xc13a1b47377a8382bd3f6f9105137c1e838758b9

Our token achtools in not updated in your API please update it as we are getting problem in listing our token on blockfolio thank you

**Comment by vastamaki** [comment]
Hey, your token is listed in /tokens endpoint already. At the moment API doesn't support fetching info about specific token (see issue #10)

**Comment by achtools** [comment]
> Hey, your token is listed in /tokens endpoint already. At the moment API doesn't support fetching info about specific token (see issue #10)

Any ideas when it will be updated in API

**Comment by vastamaki** [comment]
At least I was able to find your token from /tokens endpoint list. I am not maintainer, so can’t really say more.

**Comment by ChefKai** [comment]
Hello, we have just released this endpoint for both `v1` and `v2`; you can use it right away!

[Documentation](https://github.com/pancakeswap/pancake-info-api/blob/develop/v1-documentation.md#tokens0x)
