### ISSUE TITLE
Specific Token

### ISSUE THREAD

**Issue by RRadziejewski** [pancakeswap/pancake-info-api#44]
Hi when i want to get specific Token data i get response thst i need authenticatione token , any idea where to get that from ?

Regards

**Comment by vastamaki** [comment]
Hey, please check issue #10

**Comment by ChefKai** [comment]
Hello, we have just released this endpoint for both `v1` and `v2`; you can use it right away!

[Documentation](https://github.com/pancakeswap/pancake-info-api/blob/develop/v2-documentation.md#v2tokens0x)
