### ISSUE TITLE
How do I retrieve from this endpoint in PHP?

### ISSUE THREAD

**Issue by AndrewGoodTrade** [pancakeswap/pancake-info-api#45]
How do I retrieve from this endpoint in PHP: https://api.pancakeswap.info/api?

When I originally used it in the browser it showed me a list of tokens and their data. Now, it tells me I don't have an auth token. Where do I get this auth token and how do I connect and query via PHP? I'm trying to get all tokens, token prices and position values for my TrustWallet.

**Comment by philip** [comment]
Looks like an issue with: https://github.com/pancakeswap/pancake-info-api/issues/10

**Comment by ChefKai** [comment]
Hello, we have just released new endpoints for both `v1` and `v2` to query a token value (USD and BNB) based on his address; that should fill your requirements!

For PHP, based on your framework or version, we would suggest to use the [native curl functions](https://www.php.net/manual/en/curl.examples.php), or a 3rd-party library such as [Guzzle](https://docs.guzzlephp.org/en/stable/).

[Documentation (v2)](https://github.com/pancakeswap/pancake-info-api/blob/develop/v2-documentation.md#v2tokens0x)
