### ISSUE TITLE
Does anyone know the repository of exchange-lite subgraph? 

### ISSUE THREAD

**Issue by pnghai** [pancakeswap/pancake-info-api#46]
Hi, I saw that the underlying subgraph for this codebase is located at https://api.bscgraph.org/subgraphs/name/pancakeswap/exchange-lite, but does anyone know where the subgraph's repository is located? Is it closed source?

**Comment by ChefKai** [comment]
The subgraph PR can be found: https://github.com/pancakeswap/pancake-subgraph/pull/27
