### ISSUE TITLE
Retrieve token creationDate

### ISSUE THREAD

**Issue by alexauvray** [pancakeswap/pancake-info-api#47]
Is there a way to retrieve token creation date ?

**Comment by ChefKai** [comment]
Hello,

This is not possible to query; as the token creation date is not related to the first pair creation on PancakeSwap for this token.
Yet, if you want to get the creation date/block at which a Pair has been created, you can use the `exchange` or `exchange-lite` subgraph, and use the `timestamp` field, or wait for the end of the .info site bounty.
