### ISSUE TITLE
Specifics token show 0 price

### ISSUE THREAD

**Issue by matavispas** [pancakeswap/pancake-info-api#48]
Do you know why in several tokens when I get the price in v1, and v2, both oh them shows 0... and in pancake.exchange I can see the price??

examplhttps://api.pancakeswap.info/api/v2/tokens/0xad070194f0644cec996b9a8076eabf09e82921ea

**Comment by EPstudios** [comment]
Also interested in this as the current update returns 0 for most of the low market cap coins im looking at.

**Comment by safetimenow** [comment]
I'm also interested in that. And do your requests update the prices? I had the same price for Safemoon for about 1hour 30min (which obviously can't be true for that coin)

**Comment by FakeAK** [comment]
You can directly query the token price though a Binance Smart Chain node; or use a 3rd-party API that might fill this needs (BitQuery, Covalent etc) apparently according to this response https://github.com/pancakeswap/pancake-info-api/issues/10#issuecomment-831912699

**Comment by diamondthumbs** [comment]
Thanks for the tip @FakeAK. However, I still get nothing for certain tokens, such as HAPPY (`0xb0b924c4a31b7d4581a7f78f57cee1e65736be1d`):

```
$ curl -X GET "https://api.covalenthq.com/v1/56/address/0xb0b924c4a31b7d4581a7f78f57cee1e65736be1d/stacks/pancakeswap_v2/balances/?&key=<YOUR-KEY>"  -H "Accept: application/json" 

{"data":{"address":"0xb0b924c4a31b7d4581a7f78f57cee1e65736be1d","updated_at":"2021-05-12T22:54:01.831219521Z","next_update_at":"2021-05-12T22:59:01.831221541Z","quote_currency":"USD","chain_id":56,"pancakeswap":{"balances":[]}},"error":false,"error_message":null,"error_code":null}
```

```
$ curl https://api.pancakeswap.info/api/v2/tokens/0xb0b924c4a31b7d4581a7f78f57cee1e65736be1d
{"updated_at":1620859249429,"data":{"name":"HappyCoin","symbol":"HAPPY","price":"0","price_BNB":"0"}}
```

Is this working for anyone?

**Comment by nrileykc** [comment]
> Thanks for the tip @FakeAK. However, I still get nothing for certain tokens, such as HAPPY (`0xb0b924c4a31b7d4581a7f78f57cee1e65736be1d`):
> 
> ```
> $ curl -X GET "https://api.covalenthq.com/v1/56/address/0xb0b924c4a31b7d4581a7f78f57cee1e65736be1d/stacks/pancakeswap_v2/balances/?&key=<YOUR-KEY>"  -H "Accept: application/json" 
> 
> {"data":{"address":"0xb0b924c4a31b7d4581a7f78f57cee1e65736be1d","updated_at":"2021-05-12T22:54:01.831219521Z","next_update_at":"2021-05-12T22:59:01.831221541Z","quote_currency":"USD","chain_id":56,"pancakeswap":{"balances":[]}},"error":false,"error_message":null,"error_code":null}
> ```
> 
> ```
> $ curl https://api.pancakeswap.info/api/v2/tokens/0xb0b924c4a31b7d4581a7f78f57cee1e65736be1d
> {"updated_at":1620859249429,"data":{"name":"HappyCoin","symbol":"HAPPY","price":"0","price_BNB":"0"}}
> ```
> 
> Is this working for anyone?

No most of the new coins don't return anything for price for me either.

**Comment by Tomboi88** [comment]
Nothing for my token either! Highly frustrating

**Comment by ChefKai** [comment]
We use a selective list of trusted assets (WBNB, BUSD, USDT, USDC, UST, VAI, BTCB, WETH, BETH) that a token must have a pair with in order to start indexing his price in USD and BNB; this avoid getting corrupted data when a token is having low liquidity as well, and/or a will to harm the ecosystem. You can check the logic within the [pancakeswap/pancake-subgraph](https://github.com/pancakeswap/pancake-subgraph) repository.

**Comment by Tomboi88** [comment]
Thanks @ChefKai. Resolved for me

**Comment by GaspardC** [comment]
Hello @ChefKai , 

Do you know if we need to wait a little or meet other requirements for the API to show a price different than 0 ? 

I've created a new token wand a pair with WBNB 2 days ago and the price are still showing 0.

**Comment by grumpyshiba** [comment]
Hi @ChefKai 

https://pancakeswap.finance/info/tokens/0xAe448cB5A3ec77BA4aDcc6C8f9621e5921DCd77a

It has 3 liquidity pools including WBNB pool. However, the price is 0.

Please help
