### ISSUE TITLE
Price takes a long time to update

### ISSUE THREAD

**Issue by crox-safe** [pancakeswap/pancake-info-api#49]
I am using the api to get the prices, but the prices are usually updated within 20 minutes to an hour.

Example: https://api.pancakeswap.info/api/v2/tokens/0x0523215dcafbf4e4aa92117d13c6985a3bef27d7

In the [documentation](https://github.com/pancakeswap/pancake-info-api/blob/develop/v2-documentation.md#documentation) says `Results are cached for 5 minutes (or 300 seconds).` But it always takes a while.

Any idea?

**Comment by gogetta69** [comment]
Right, it was working at first. It's just been the last couple of day this has been happening.

**Comment by Ne0-d3gen** [comment]
Same issue here, it is taking between 20-45 minutes for the price of a token to be updated using the API (v2) which is obviously of no use for most altcoins whose price changes significantly every few minutes @ChefKai can you look into this please

**Comment by Ne0-d3gen** [comment]
Also, I have noticed that when the price does eventually update, it bears no resemblance whatsoever to the actual price as shown on the pancakeswap exchange!

**Comment by orioltobar** [comment]
I have the same issue, the price takes more than an hour to update and as @tomheaps said, the actual price is not accurate. The token is using V2.

**Comment by crox-safe** [comment]
According to @ChefKai it is a problem with the bsc nodes.

See: [https://github.com/pancakeswap/pancake-subgraph/issues/50](url)
