### ISSUE TITLE
Radditarium token not updated in API V2

### ISSUE THREAD

**Issue by radditarium** [pancakeswap/pancake-info-api#58]
Hello our token details not updated in V2 please have a look
Contract
0xbb8170ad35325522c0026d67584d4fefbd08b750
https://exchange.pancakeswap.finance/#/swap?outputCurrency=0xbb8170ad35325522c0026d67584d4fefbd08b750

**Comment by radditarium** [comment]
@ChefKai please have a look or give me your telegram so I can get faster support thanks

**Comment by ChefKai** [comment]
Fixed.
