### ISSUE TITLE
Can i auto buy and sell using pancakeswap api ?

### ISSUE THREAD

**Issue by fmsimsek** [pancakeswap/pancake-info-api#59]
Hello sir,
Can i auto buy and sell using pancakeswap api ?

**Comment by gogetta69** [comment]
No, but with python and web3 this simple example code will work.

https://zhiyan.blog/2021/05/23/how-to-create-a-pancakeswap-bot-using-python/

Not sure but I think the pancakeswap's function hes calling in that example is only for tokens that doesn't require a fee. So for the tokens that require fees you will need to run "swapExactETHForTokensSupportingFeeOnTransferTokens".

Check the contract for any other functions you will need to use. Also make sure to load the full Contract ABI before trying to run other functions. https://bscscan.com/address/0x10ed43c718714eb63d5aa57b78b54704e256024e#writeContract

**Comment by fmsimsek** [comment]
Thank you sir for answer.

**Comment by ZainAchak** [comment]
Go for this straight and simple https://youtu.be/cSel-wyrTFI

**Comment by ZainAchak** [comment]
https://youtu.be/cSel-wyrTFI

**Comment by benhibi** [comment]
> https://youtu.be/cSel-wyrTFI

Please help me sell code pancakeswap, thanks
