### ISSUE TITLE
Please update our token in your API

### ISSUE THREAD

**Issue by radditarium** [pancakeswap/pancake-info-api#61]
Hello we are trading in pancakeswap V2 from last 15 days

https://api.pancakeswap.info/api/v2/tokens/0xbb8170ad35325522c0026d67584d4fefbd08b750

Please update 

Thanks

**Comment by YellAppOfficial** [comment]
We are wondering the same thing - we noticed some other tokens that are included in the API and are only 3 days old.  Is there something that we need to do to make the API aware of our tokens?

**Comment by ChefKai** [comment]
Fixed.
