### ISSUE TITLE
Request: Could you update iHODL token in your API?

### ISSUE THREAD

**Issue by investhodl** [pancakeswap/pancake-info-api#63]
Hello, 

Could you update iHODL Token in your Api? 

https://api.pancakeswap.info/api/v2/tokens/0x9cadb2f8adaf224011500bea8d2a38356540de71

https://bscscan.com/address/0x9cadb2f8adaf224011500bea8d2a38356540de71

Thanks!

**Comment by ChefKai** [comment]
Fixed.
