### ISSUE TITLE
Pancakeswap API doesn't recognize cMATIC token- Please help

### ISSUE THREAD

**Issue by Dikshasoft** [pancakeswap/pancake-info-api#64]
Dear Team,

It seems Pancakeswap API doesn't recognize our token which is being listed for over two weeks now. could you please check?
https://api.pancakeswap.info/api/v2/tokens/0xf19438b660067d2b68f766ff63dabf1d4f603253
https://api.pancakeswap.info/api/tokens/0xf19438b660067d2b68f766ff63dabf1d4f603253

BSCScan: https://bscscan.com/token/0xf19438b660067d2b68f766ff63dabf1d4f603253

To check this deeper, I created another token just to ensure we did not miss anything on our side we created another one but the same result, can you please assist here?
https://api.pancakeswap.info/api/v2/tokens/0x198deDfEB86eDa80836FE47FE8A0B496E71b71a9
https://api.pancakeswap.info/api/tokens/0x198deDfEB86eDa80836FE47FE8A0B496E71b71a9

BSCScan: https://bscscan.com/token/0x198deDfEB86eDa80836FE47FE8A0B496E71b71a9

**They all throw error with**
{"error":{"code":404,"message":"Not found"}}

**Comment by Dikshasoft** [comment]
@ChefKai due to these issues our listing request already rejected :( so I would really appreciate your support here.

Thank you in advance.

**Comment by Dikshasoft** [comment]
@ChefKai I'm sure you must be busy but I really need to have the below token listed on your API?
https://api.pancakeswap.info/api/v2/tokens/0x198deDfEB86eDa80836FE47FE8A0B496E71b71a9
https://api.pancakeswap.info/api/tokens/0x198deDfEB86eDa80836FE47FE8A0B496E71b71a9

BSCScan: https://bscscan.com/token/0x198deDfEB86eDa80836FE47FE8A0B496E71b71a9

Looking forward for your support.

**Comment by Dikshasoft** [comment]
> @ChefKai

Hi @ChefKai  did you get a chance to look into this, please? excuse my continuous ask but this is a big blocker for us now.
Your help would be appreciated.

**Comment by Dikshasoft** [comment]
> > @ChefKai
> 
> Hi @ChefKai did you get a chance to look into this, please? excuse my continuous ask but this is a big blocker for us now.
> Your help would be appreciated.

@ChefKai - Can you please check on this and confirm, the API needs to work before we can request CMC/CG.

Thank you in advance

**Comment by Dikshasoft** [comment]
@ChefKai Looks like the API started working TODAY FOR my old contract (WAS LISTED 29TH ON PANCAKE), Does that mean the new one(https://api.pancakeswap.info/api/v2/tokens/0x198deDfEB86eDa80836FE47FE8A0B496E71b71a9) takes another 10 days to sync and available ?? does it take that long?

![image](https://user-images.githubusercontent.com/25227385/122095200-5ae84400-ce0d-11eb-8019-1790ae8570c2.png)

**Comment by ChefKai** [comment]
Fixed, but you need a minimum of 10BNB of liquidity before the subgraph returns any price to avoid miss-calculating due to low liquidity and test tokens,

**Comment by Dikshasoft** [comment]
Thank you Chef for this , its much appreciated,


can I ask what was the issues, its almost took 1 month to fix this.
