### ISSUE TITLE
ASSG Token not found in Pancakeswap API

### ISSUE THREAD

**Issue by FreePatriot76** [pancakeswap/pancake-info-api#68]
To whom it may concern,

My token Assgard (ASSG)  CA: 0x7c52e19e4d350189bcdfb7f7a0868117e9f195e5  is not showing up in your pancakeswap api.  Because of this Blockfolio will not let me list on their site.  Can you please correct ASAP.

We ended up relaunching our project with a new contract address but it looks like your api has our old contract address.

New contract address: 0x7c52e19e4d350189bcdfb7f7a0868117e9f195e5  
Old contract address: 0x9B2411dD7002aef8e27C436EA0f0A75C640361f7

Can you please correct.

**Comment by ChefKai** [comment]
Fixed.

```
"data": {
    "name": "Assgard",
    "symbol": "ASSG",
    "price": "0.000000000036127162437430134358124044405",
    "price_BNB": "0.0000000000001209618119678308436031960790948"
}
```
