### ISSUE TITLE
Problem with API v2

### ISSUE THREAD

**Issue by vladigor777** [pancakeswap/pancake-info-api#72]
Hi! I try to get price of Roocoin via API.

But link https://api.pancakeswap.info/api/v2/tokens/0x30b29c6c03546f6395ddb454538d0eb7e4a6e32f don't show correct price.

Help me please.

**Comment by Loque18** [comment]
Im having the same issue

**Comment by nexo01** [comment]
Having the same issue. Tells me "404 Not found" but Im able to trade the token

**Comment by VainToken** [comment]
+1, the same problem https://api.pancakeswap.info/api/v2/tokens/0x7d03d1ae4de2702d282540782c595027bdb9d76e

**Comment by nwhite89** [comment]
Ditto

**Comment by VainToken** [comment]
@vladigor777 I see it's working now for your token. What did you do? :)

**Comment by Tomboi88** [comment]
> Hi! I try to get price of Roocoin via API.
> 
> But link https://api.pancakeswap.info/api/v2/tokens/0x30b29c6c03546f6395ddb454538d0eb7e4a6e32f don't show correct price.
> 
> Help me please.

Hi, I can see your price is now working! Do you know the fix?

**Comment by Tomboi88** [comment]
Same issue here, plenty of liquidity, 2 months old.

PCS, Please sort this issue or inform us how to fix.

Thanks

**Comment by ChefKai** [comment]
Fixed.

**Comment by Tomboi88** [comment]
Thanks @ChefKai
