### ISSUE TITLE
Pancake api is down?

### ISSUE THREAD

**Issue by atropos0902** [pancakeswap/pancake-info-api#75]
What's wrong with following apis?

```
https://api.pancakeswap.info/api/v2/tokens
https://api.pancakeswap.info/api/v2/pairs
```

It suddenly stops working and is returning `500` error now.
Not sure what's wrong there.

**Comment by TundraFizz** [comment]
I'm getting the same issue as well

https://api.pancakeswap.info/api/v2/summary

```
{"error":{"code":500,"message":"Network error: Response not successful: Received status code 502"}}
```

**Comment by muz-6** [comment]
same here

**Comment by atropos0902** [comment]
Seems like it's fixed now.

**Comment by CasualEngineerZombie** [comment]
It's not working on my end. June 25, 2021

**Comment by ChefKai** [comment]
Fixed.
