### ISSUE TITLE
/v2/summary endpoint not working

### ISSUE THREAD

**Issue by rahultrivedi180** [pancakeswap/pancake-info-api#76]
```json
{"error":{"code":500,"message":"first block was not fetched"}}
```

getting this error while calling: <https://api.pancakeswap.info/api/v2/summary>

**Comment by vaibhavmehrotraml** [comment]
Did you find a solution @rahultrivedi180?

**Comment by rahultrivedi180** [comment]
> Did you find a solution @rahultrivedi180?

Workaround is like one need to deploy own subgraph and everything is from scratch.
