### ISSUE TITLE
Token not found in API, 404

### ISSUE THREAD

**Issue by VainToken** [pancakeswap/pancake-info-api#78]
Hi guys! The api return 404 not found for our token https://api.pancakeswap.info/api/v2/tokens/0x6067652fe687aa221b6f86f398af4d0fe9bf45e3

How can we fix that?

We cannot apply to CMC/blockfolio without this api properly working

**Comment by VainToken** [comment]
@ChefKai could you please help me with the issue?

**Comment by ChefKai** [comment]
Fixed.
