### ISSUE TITLE
Access to Syrup Pools stacking info

### ISSUE THREAD

**Issue by letehaha** [pancakeswap/pancake-info-api#83]
Hey guys, it is rather not an issue but a question. Sorry if it is super obvious, but I'm just a newbie here. Am I able to somehow check current staking info for the selected account id? For example, I asked some user to connect MetaMask to my website. He accepted the request and now I know his account id. Using BscScan I can check how many coins he sent to the PancakeSwap, but there is no info about how many coins he is staked in the pool and what is his current reward (I hope I'm using the terminology correctly).
Thanks in advance!

**Comment by ChefKai** [comment]
Hello, no this doesn't exist on the current API and this feature is not planned for it, we are planning to get a custom API for it but this is still a work in progress and no ETA can be shared at this time. To get this data, please refer to the implementation at [pancakeswap/pancake-frontend](https://github.com/pancakeswap/pancake-frontend) repository.

**Comment by letehaha** [comment]
Well, that makes sense about the repo. Thanks, @ChefKai!

**Comment by Robin-Sch** [comment]
Did you figure this out? If so could you please help me with it

**Comment by letehaha** [comment]
@Robin-Sch nah, I just switched to other stuff :D

**Comment by Robin-Sch** [comment]
Oh yikes, well thanks anyway

**Comment by Robin-Sch** [comment]
https://gist.github.com/numtel/ce52b7d07cc62412eb5207b29f119d3b

This gist shows how to do it in nodejs (javascript)
