### ISSUE TITLE
Liquidity API 

### ISSUE THREAD

**Issue by SuperMario-Devs** [pancakeswap/pancake-info-api#84]
Hi,

I am trying to retrieve the liquidity amount to my excell sheet to calculate value of the paired token on Pancakeswap.
For some reason the API request do not seem to work.
The Pair is WBNB/WHEAT and contract adress is 0xD58F6FC430BFd33e07566541D91b80143d1D3BB5.

Is there a simple way to obtain the liquidity total of the pool and export this to excell?

Thank you for your help!

Best Mario

**Comment by ArchTaqi** [comment]
@SuperMario-Devs did you find any solution to this?
