### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by whittlem** [pancakeswap/pancake-info-api#91]
I don't see an API method to retrieve historical data for a market in the documentation. Does it exist?

**Comment by ChefKai** [comment]
Hello, no this doesn't exist on the current API and this feature is not planned for it, in order to achieve this, please use the subgraph directly at [pancakeswap/pancake-subgraph](https://github.com/pancakeswap/pancake-subgraph).

**Comment by whittlem** [comment]
Ok, thank you.
